// Code generated by Slice Machine. DO NOT EDIT.

import Brief from './Brief';
import CityList from './CityList';
import ContactForm from './ContactForm';
import EditorChoice from './EditorChoice';
import HeroSlice from './HeroSlice';
import Image from './Image';
import MostPopular from './MostPopular';
import NewsLetterSection from './NewsLetterSection';
import PageTitle from './PageTitle';
import Quote from './Quote';
import RightText from './RightText';
import SectionHeader from './SectionHeader';
import SplashBg from './SplashBg';
import TableOfContent from './TableOfContent';
import Text from './Text';

export {
	Brief,
	CityList,
	ContactForm,
	EditorChoice,
	HeroSlice,
	Image,
	MostPopular,
	NewsLetterSection,
	PageTitle,
	Quote,
	RightText,
	SectionHeader,
	SplashBg,
	TableOfContent,
	Text,
};

export const components = {
	brief: Brief,
	city_list: CityList,
	contact_form: ContactForm,
	editor_choice: EditorChoice,
	hero_slice: HeroSlice,
	image: Image,
	most_popular: MostPopular,
	news_letter_section: NewsLetterSection,
	page_title: PageTitle,
	quote: Quote,
	right_text: RightText,
	section_header: SectionHeader,
	splash_bg: SplashBg,
	table_of_content: TableOfContent,
	text: Text,
};
